INSERT INTO ROLE VALUES (1, 'ROLE_USER' ), (2, 'ROLE_OWNER');

INSERT INTO ADDRESS (APARTMENT_NUMBER, CITY, HOUSE_NUMBER, STREET, ZIPCODE) VALUES ( '10', 'Warszawa', '20', 'Aleje jerozolimskie', '20-313' );
INSERT INTO ADDRESS (APARTMENT_NUMBER, CITY, HOUSE_NUMBER, STREET, ZIPCODE) VALUES ( '12', 'Piaseczno', '13', 'Warszawska', '12-313' );
INSERT INTO ADDRESS (APARTMENT_NUMBER, CITY, HOUSE_NUMBER, STREET, ZIPCODE) VALUES ( '1', 'Warszawa', '2', 'Aleje ujazdowski', '20-313' );

INSERT INTO COMPANY (NAME, TAX_NUMBER, ADDRESS_ID) VALUES ( 'Company1', '123-456-78-19', 3);

INSERT INTO USER (EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, ADDRESS_ID, COMPANY_ID, ROLE_ID) VALUES ('lukasz.malinowski10@gmail.com', 'Łukasz', 'Malinowski', '$2a$10$fFBNHqZJ27CRlhuehipebex7QXU9xHK9ORQKY8RURU59mLNQc0AJG', '500-600-700', 1, 1, 1);
INSERT INTO USER (EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, ADDRESS_ID, COMPANY_ID, ROLE_ID) VALUES ('owner@owner.com', 'Service', 'Owner', '$2a$10$fFBNHqZJ27CRlhuehipebex7QXU9xHK9ORQKY8RURU59mLNQc0AJG', '600-600-700', null, null, 1);

INSERT INTO COMPANY_EMPLOYEES (COMPANY_ID, EMPLOYEES_ID) VALUES ( 1, 1 );

INSERT INTO GARAGE (NAME, ADDRESS_ID, OWNER_ID) VALUES ( 'Car-service', 2, 2);

INSERT INTO GARAGE_AVAILABLE_DATES (GARAGE_ID, AVAILABLE_DATES) VALUES (1, '2021-07-20T10:00:00.000Z');
INSERT INTO GARAGE_AVAILABLE_DATES (GARAGE_ID, AVAILABLE_DATES) VALUES (1, '2021-06-13T12:30:00.000Z');
INSERT INTO GARAGE_AVAILABLE_DATES (GARAGE_ID, AVAILABLE_DATES) VALUES (1, '2021-06-13T15:30:00.000Z');

INSERT INTO CAR (MARK, MODEL, NET_ENGINE_POWER, PRODUCTION_YEAR, REGISTRATION_NUMBER, VIN_NUMBER, OWNER_ID) VALUES ('Fiat', 'Punto', 60, 1996, 'WPR12345', '1234567890', 1);

INSERT INTO MECHANIC (HOURLY_RATE, NAME, SURNAME, GARAGE_ID) VALUES (30, 'Tadeusz', 'Nowak', 1);
INSERT INTO MECHANIC (HOURLY_RATE, NAME, SURNAME, GARAGE_ID) VALUES (25, 'Grzegorz', 'Lasocki', 1);

INSERT INTO PART (NAME, PRICE, PRODUCER) VALUES ( 'Opony zimowe', 200, 'Michelin');
INSERT INTO PART (NAME, PRICE, PRODUCER) VALUES ( 'Tarcza hamulcowa', 500, 'Brembo');
INSERT INTO PART (NAME, PRICE, PRODUCER) VALUES ( 'Wycieraczki', 100, 'Bosch');

INSERT INTO REPAIR (DESCRIPTION, RECEIVE_DATE_TIME, RETURN_DATE_TIME, CAR_ID, GARAGE_ID) VALUES ( 'Mój samochód nie hamuje', '2021-06-13T10:00:00.000Z', null, 1, 1);

INSERT INTO REPAIR_PARTS (REPAIR_ID, PARTS_ID) VALUES ( 1, 1);
INSERT INTO REPAIR_PARTS (REPAIR_ID, PARTS_ID) VALUES ( 1, 2);

INSERT INTO MECHANIC_REPAIR (HOURS, NOTES, MECHANIC_ID, REPAIR_ID) VALUES (6, 'Some notes', 1, 1 );
INSERT INTO MECHANIC_REPAIR (HOURS, NOTES, MECHANIC_ID, REPAIR_ID) VALUES (6, null, 2, 1 );